In [ ]:
! pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.10/dist-packages (2.14.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (23.5.26)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.9.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (16.0.6)
Requirement already satisfied: ml-dtypes==0.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: numpy>=1.23.5 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.23.5)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow) (23.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.20.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow) (67.7.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (4.5.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.34.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.59.2)
Requirement already satisfied: tensorboard<2.15,>=2.14 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.14.1)
Requirement already satisfied: tensorflow-estimator<2.15,>=2.14.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.14.0)
Requirement already satisfied: keras<2.15,>=2.14.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.14.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow) (0.41.3)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.15,>=2.14->tensorflow) (2.17.3)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.15,>=2.14->tensorflow) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.15,>=2.14->tensorflow) (3.5.1)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.15,>=2.14->tensorflow) (2.31.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.15,>=2.14->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.15,>=2.14->tensorflow) (3.0.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow) (5.3.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.15,>=2.14->tensorflow) (1.3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow) (2023.7.22)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.15,>=2.14->tensorflow) (2.1.3)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow) (0.5.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.15,>=2.14->tensorflow) (3.2.2)

In [ ]:
! pip install pytorch-tabnet

Requirement already satisfied: pytorch-tabnet in /usr/local/lib/python3.10/dist-packages (4.1.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from pytorch-tabnet) (1.23.5)
Requirement already satisfied: scikit_learn>0.21 in /usr/local/lib/python3.10/dist-packages (from pytorch-tabnet) (1.2.2)
Requirement already satisfied: scipy>1.4 in /usr/local/lib/python3.10/dist-packages (from pytorch-tabnet) (1.11.3)
Requirement already satisfied: torch>=1.3 in /usr/local/lib/python3.10/dist-packages (from pytorch-tabnet) (2.1.0+cu118)
Requirement already satisfied: tqdm>=4.36 in /usr/local/lib/python3.10/dist-packages (from pytorch-tabnet) (4.66.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit_learn>0.21->pytorch-tabnet) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit_learn>0.21->pytorch-tabnet) (3.2.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.3->pytorch-tabnet) (3.13.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch>=1.3->pytorch-tabnet) (4.5.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.3->pytorch-tabnet) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.3->pytorch-tabnet) (3.2.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.3->pytorch-tabnet) (3.1.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.3->pytorch-tabnet) (2023.6.0)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.3->pytorch-tabnet) (2.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.3->pytorch-tabnet) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.3->pytorch-tabnet) (1.3.0)

In [ ]:
#Importing Libary
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
url = '/content/drive/MyDrive/Modul 5 - Transfer Learning/Dataset/income.csv'
df = pd.read_csv(url)
df.tail()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income_>50K
43952,52,Private,68982,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,1
43953,19,Private,116562,HS-grad,9,Never-married,Other-service,Own-child,White,Female,0,0,40,United-States,0
43954,30,Private,197947,Some-college,10,Divorced,Sales,Not-in-family,White,Male,0,0,58,United-States,0
43955,46,Private,97883,Bachelors,13,Never-married,Sales,Not-in-family,White,Female,0,0,35,United-States,0
43956,30,Private,375827,HS-grad,9,Never-married,Handlers-cleaners,Other-relative,White,Male,0,0,40,United-States,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43957 entries, 0 to 43956
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              43957 non-null  int64
 1   workclass        41459 non-null  object
 2   fnlwgt           43957 non-null  int64
 3   education        43957 non-null  object
 4   educational-num  43957 non-null  int64
 5   marital-status   43957 non-null  object
 6   occupation       41451 non-null  object
 7   relationship     43957 non-null  object
 8   race             43957 non-null  object
 9   gender           43957 non-null  object
 10  capital-gain     43957 non-null  int64
 11  capital-loss     43957 non-null  int64
 12  hours-per-week   43957 non-null  int64
 13  native-country   43194 non-null  object
 14  income_>50K      43957 non-null  int64
dtypes: int64(7), object(8)
memory usage: 5.0+ MB

In [ ]:
df.isnull().sum()

age                   0
workclass          2498
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         2506
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      763
income_>50K           0
dtype: int64

In [ ]:
# Menghapus kolom dengan nilai kosong dalam bentuk objek
df.dropna(subset=['workclass', 'occupation', 'native-country'], inplace=True)
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income_>50K
0,67,Private,366425,Doctorate,16,Divorced,Exec-managerial,Not-in-family,White,Male,99999,0,60,United-States,1
1,17,Private,244602,12th,8,Never-married,Other-service,Own-child,White,Male,0,0,15,United-States,0
2,31,Private,174201,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,1
3,58,State-gov,110199,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,0
4,25,State-gov,149248,Some-college,10,Never-married,Other-service,Not-in-family,Black,Male,0,0,40,United-States,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43952,52,Private,68982,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,1
43953,19,Private,116562,HS-grad,9,Never-married,Other-service,Own-child,White,Female,0,0,40,United-States,0
43954,30,Private,197947,Some-college,10,Divorced,Sales,Not-in-family,White,Male,0,0,58,United-States,0
43955,46,Private,97883,Bachelors,13,Never-married,Sales,Not-in-family,White,Female,0,0,35,United-States,0
43956,30,Private,375827,HS-grad,9,Never-married,Handlers-cleaners,Other-relative,White,Male,0,0,40,United-States,0

In [ ]:
df.duplicated().sum()

41

In [ ]:
df = df.drop_duplicates()

In [ ]:
# Loop melalui kolom-kolom DataFrame
for column in df.columns:
    le = LabelEncoder()
    if df[column].dtype == 'object':
        df[column] = le.fit_transform(df[column])
df.head()

<ipython-input-26-700ac5ae8571>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = le.fit_transform(df[column])
<ipython-input-26-700ac5ae8571>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = le.fit_transform(df[column])
<ipython-input-26-700ac5ae8571>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = le.fit_transform(df[column])
<ipython-input-26-700ac5ae8571>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = le.fit_transform(df[column])
<ipython-input-26-700ac5ae8571>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = le.fit_transform(df[column])
<ipython-input-26-700ac5ae8571>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = le.fit_transform(df[column])
<ipython-input-26-700ac5ae8571>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = le.fit_transform(df[column])
<ipython-input-26-700ac5ae8571>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = le.fit_transform(df[column])

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income_>50K
0,67,2,366425,10,16,0,3,1,4,1,99999,0,60,38,1
1,17,2,244602,2,8,4,7,3,4,1,0,0,15,38,0
2,31,2,174201,9,13,2,3,0,4,1,0,0,40,38,1
3,58,5,110199,5,4,2,13,0,4,1,0,0,40,38,0
4,25,5,149248,15,10,4,7,1,2,1,0,0,40,38,0

In [ ]:
# Membagi dataset menjadi data pelatihan dan pengujian
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

In [ ]:
# Menggunakan pustaka TabNet

from pytorch_tabnet.tab_model import TabNetClassifier

clf = TabNetClassifier()
clf.fit(
    X_train=train_df.drop('income_>50K', axis=1).values,
    y_train=train_df['income_>50K'].values,
    eval_set=[(train_df.drop('income_>50K', axis=1).values, train_df['income_>50K'].values),
              (test_df.drop('income_>50K', axis=1).values, test_df['income_>50K'].values)]
)

/usr/local/lib/python3.10/dist-packages/pytorch_tabnet/abstract_model.py:82: UserWarning: Device used : cpu
  warnings.warn(f"Device used : {self.device}")

epoch 0  | loss: 0.50657 | val_0_auc: 0.63158 | val_1_auc: 0.63508 |  0:00:03s
epoch 1  | loss: 0.39983 | val_0_auc: 0.66057 | val_1_auc: 0.66284 |  0:00:05s
epoch 2  | loss: 0.37651 | val_0_auc: 0.72257 | val_1_auc: 0.7275  |  0:00:07s
epoch 3  | loss: 0.36639 | val_0_auc: 0.81634 | val_1_auc: 0.81632 |  0:00:09s
epoch 4  | loss: 0.36386 | val_0_auc: 0.86061 | val_1_auc: 0.86628 |  0:00:12s
epoch 5  | loss: 0.35819 | val_0_auc: 0.87248 | val_1_auc: 0.87447 |  0:00:14s
epoch 6  | loss: 0.35577 | val_0_auc: 0.88057 | val_1_auc: 0.88221 |  0:00:16s
epoch 7  | loss: 0.35486 | val_0_auc: 0.88544 | val_1_auc: 0.89307 |  0:00:19s
epoch 8  | loss: 0.35213 | val_0_auc: 0.88699 | val_1_auc: 0.89275 |  0:00:22s
epoch 9  | loss: 0.35201 | val_0_auc: 0.89006 | val_1_auc: 0.89092 |  0:00:24s
epoch 10 | loss: 0.34686 | val_0_auc: 0.89428 | val_1_auc: 0.89507 |  0:00:26s
epoch 11 | loss: 0.346   | val_0_auc: 0.89291 | val_1_auc: 0.89527 |  0:00:28s
epoch 12 | loss: 0.34542 | val_0_auc: 0.89301 | val_1_auc: 0.89557 |  0:00:30s
epoch 13 | loss: 0.34641 | val_0_auc: 0.89284 | val_1_auc: 0.89733 |  0:00:33s
epoch 14 | loss: 0.34495 | val_0_auc: 0.89166 | val_1_auc: 0.89618 |  0:00:36s
epoch 15 | loss: 0.341   | val_0_auc: 0.89719 | val_1_auc: 0.89938 |  0:00:38s
epoch 16 | loss: 0.3414  | val_0_auc: 0.89612 | val_1_auc: 0.90023 |  0:00:40s
epoch 17 | loss: 0.34098 | val_0_auc: 0.89589 | val_1_auc: 0.8979  |  0:00:43s
epoch 18 | loss: 0.34038 | val_0_auc: 0.89694 | val_1_auc: 0.89938 |  0:00:45s
epoch 19 | loss: 0.33994 | val_0_auc: 0.89855 | val_1_auc: 0.90111 |  0:00:48s
epoch 20 | loss: 0.33918 | val_0_auc: 0.90004 | val_1_auc: 0.90348 |  0:00:51s
epoch 21 | loss: 0.33458 | val_0_auc: 0.90075 | val_1_auc: 0.9026  |  0:00:53s
epoch 22 | loss: 0.33773 | val_0_auc: 0.89716 | val_1_auc: 0.89976 |  0:00:56s
epoch 23 | loss: 0.33768 | val_0_auc: 0.89958 | val_1_auc: 0.90261 |  0:00:58s
epoch 24 | loss: 0.33592 | val_0_auc: 0.90031 | val_1_auc: 0.90395 |  0:01:00s
epoch 25 | loss: 0.33605 | val_0_auc: 0.8988  | val_1_auc: 0.90332 |  0:01:02s
epoch 26 | loss: 0.33336 | val_0_auc: 0.90246 | val_1_auc: 0.90391 |  0:01:04s
epoch 27 | loss: 0.3328  | val_0_auc: 0.90184 | val_1_auc: 0.90388 |  0:01:07s
epoch 28 | loss: 0.33042 | val_0_auc: 0.90177 | val_1_auc: 0.90317 |  0:01:10s
epoch 29 | loss: 0.33232 | val_0_auc: 0.90223 | val_1_auc: 0.90378 |  0:01:12s
epoch 30 | loss: 0.3323  | val_0_auc: 0.89958 | val_1_auc: 0.9024  |  0:01:14s
epoch 31 | loss: 0.33053 | val_0_auc: 0.89934 | val_1_auc: 0.90245 |  0:01:17s
epoch 32 | loss: 0.333   | val_0_auc: 0.90286 | val_1_auc: 0.90595 |  0:01:19s
epoch 33 | loss: 0.33103 | val_0_auc: 0.90246 | val_1_auc: 0.90512 |  0:01:22s
epoch 34 | loss: 0.33153 | val_0_auc: 0.90343 | val_1_auc: 0.90545 |  0:01:25s
epoch 35 | loss: 0.33063 | val_0_auc: 0.90418 | val_1_auc: 0.90766 |  0:01:27s
epoch 36 | loss: 0.32796 | val_0_auc: 0.90417 | val_1_auc: 0.90701 |  0:01:29s
epoch 37 | loss: 0.32806 | val_0_auc: 0.90444 | val_1_auc: 0.90786 |  0:01:31s
epoch 38 | loss: 0.32804 | val_0_auc: 0.9047  | val_1_auc: 0.90763 |  0:01:34s
epoch 39 | loss: 0.33344 | val_0_auc: 0.90212 | val_1_auc: 0.90593 |  0:01:36s
epoch 40 | loss: 0.32925 | val_0_auc: 0.90425 | val_1_auc: 0.90583 |  0:01:39s
epoch 41 | loss: 0.3269  | val_0_auc: 0.90533 | val_1_auc: 0.90788 |  0:01:42s
epoch 42 | loss: 0.32658 | val_0_auc: 0.90503 | val_1_auc: 0.90647 |  0:01:44s
epoch 43 | loss: 0.32673 | val_0_auc: 0.90587 | val_1_auc: 0.90814 |  0:01:46s
epoch 44 | loss: 0.32852 | val_0_auc: 0.90589 | val_1_auc: 0.90926 |  0:01:48s
epoch 45 | loss: 0.3265  | val_0_auc: 0.9067  | val_1_auc: 0.90916 |  0:01:50s
epoch 46 | loss: 0.32662 | val_0_auc: 0.90613 | val_1_auc: 0.90808 |  0:01:52s
epoch 47 | loss: 0.32537 | val_0_auc: 0.90693 | val_1_auc: 0.9091  |  0:01:55s
epoch 48 | loss: 0.32447 | val_0_auc: 0.90759 | val_1_auc: 0.90859 |  0:01:58s
epoch 49 | loss: 0.32727 | val_0_auc: 0.90678 | val_1_auc: 0.90734 |  0:02:01s
epoch 50 | loss: 0.32504 | val_0_auc: 0.90683 | val_1_auc: 0.90794 |  0:02:03s
epoch 51 | loss: 0.32326 | val_0_auc: 0.90775 | val_1_auc: 0.90814 |  0:02:05s
epoch 52 | loss: 0.32352 | val_0_auc: 0.90822 | val_1_auc: 0.90849 |  0:02:07s
epoch 53 | loss: 0.3249  | val_0_auc: 0.90754 | val_1_auc: 0.9059  |  0:02:09s
epoch 54 | loss: 0.32759 | val_0_auc: 0.90734 | val_1_auc: 0.90809 |  0:02:12s

Early stopping occurred at epoch 54 with best_epoch = 44 and best_val_1_auc = 0.90926

/usr/local/lib/python3.10/dist-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

In [ ]:
# Melakukan prediksi pada data pengujian

from sklearn.metrics import accuracy_score

predictions = clf.predict(test_df.drop('income_>50K', axis=1).values)
accuracy = accuracy_score(test_df['income_>50K'].values, predictions)

print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.85

In [ ]:
# Mengkonversi prediksi menjadi label (0 atau 1)
predicted_labels = np.round(predictions).flatten().astype(int)

# Hasil prediksi
print("Hasil prediksi:")
print(predicted_labels)

Hasil prediksi:
[0 0 0 ... 0 0 0]

In [ ]:
# Calculate and display the classification report
target_names = ['Class 0', 'Class 1']
print(classification_report(test_df['income_>50K'].values, predicted_labels, target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.89      0.92      0.90      6137
     Class 1       0.72      0.65      0.68      2001

    accuracy                           0.85      8138
   macro avg       0.80      0.78      0.79      8138
weighted avg       0.85      0.85      0.85      8138